### ISSUE TITLE
Should the Docker version be working?

### ISSUE THREAD

**Issue by randykerber** [openphacts/Void-Editor2#3] opened 2017-02-05 00:07 UTC
Tried running this in Docker container and it failed.  Maybe it's not ready yet?

I went through all the UI forms to create a void file, then got a `VoidValidatorException`.

I did make up values for some entries, not sure if that should have mattered.

Here's the error stack dump below (and attached a couple log files I pulled out of the docker container):

[logs.zip](https://github.com/openphacts/Void-Editor2/files/752657/logs.zip)

```
message uk.ac.manchester.cs.datadesc.validator.rdftools.VoidValidatorException: The editor created a not valid file - please contact Lefteris.

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: uk.ac.manchester.cs.datadesc.validator.rdftools.VoidValidatorException: The editor created a not valid file - please contact Lefteris.
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

uk.ac.manchester.cs.datadesc.validator.rdftools.VoidValidatorException: The editor created a not valid file - please contact Lefteris.
	editor.domain.VoidTurtle.validateRDFForOPS(VoidTurtle.java:539)
	editor.domain.VoidTurtle.createVoid(VoidTurtle.java:294)
	editor.service.VoidService.getLocation(VoidService.java:87)
	editor.rest.VoidRestService.getVoidFile(VoidRestService.java:79)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

```

**Comment by stain** [comment] 2017-02-08 10:39
I managed to reproduce with the same error. It's probably because I updated the dependencies of the void validator (to avoid a very old SNAPSHOT).

```
Validation report for: (<http://rdfs.org/ns/void#DatasetDescription>) <file:/usr/local/tomcat/temp/void8854461110473330942.ttl>
	 No Errors found!
Validation report for: (<http://rdfs.org/ns/void#Dataset>) <http://www.openphacts.org/d5986e26-9f06-4f1a-9a1a-8f5bab0973e3>
	ERROR: Found: <http://www.openphacts.org/d5986e26-9f06-4f1a-9a1a-8f5bab0973e3> <http://rdfs.org/ns/void#dataDump> <http://example.com/rdf.gz>
		http://example.com/rdf.gz has not been typed, and does not meet the requirements of any known type. 
	Warning: No statements found with predicate: <http://purl.org/dc/terms/subject>
		Please add one or more statement with predicate <http://purl.org/dc/terms/subject> and type A URI.
	Warning: No statements found with predicate: <http://purl.org/pav/previousVersion>
		Please add one or more statement with predicate <http://purl.org/pav/previousVersion> and type  A String
	Warning: No statements found with predicate: <http://purl.org/dc/terms/accuralPeriodicity>
		Please add one or more statement with predicate <http://purl.org/dc/terms/accuralPeriodicity> and type http://vocabularies.bridgedb.org/ops#FrequencyOfChange URI for example: [http://purl.org/cld/freq/weekly, http://purl.org/cld/freq/semiweekly, http://purl.org/cld/freq/continuous, http://purl.org/cld/freq/triennial, http://purl.org/cld/freq/biweekly, http://purl.org/cld/freq/monthly, http://purl.org/cld/freq/threeTimesAWeek, http://purl.org/cld/freq/daily, http://purl.org/cld/freq/annual, http://purl.org/cld/freq/threeTimesAMonth, http://purl.org/cld/freq/semimonthly, http://purl.org/cld/freq/irregular, http://purl.org/cld/freq/bimonthly, http://purl.org/cld/freq/semiannual, http://purl.org/cld/freq/biennial, http://purl.org/cld/freq/threeTimesAYear, http://purl.org/cld/freq/quarterly]
	ERROR: Found: <http://www.openphacts.org/d5986e26-9f06-4f1a-9a1a-8f5bab0973e3> <http://purl.org/pav/derivedFrom> <http://raw.githubusercontent.com/openphacts/ops-platform-setup/2.0.0/void/drugbank_4.1_void.ttl#drugbank-rdf>
		http://raw.githubusercontent.com/openphacts/ops-platform-setup/2.0.0/void/drugbank_4.1_void.ttl#drugbank-rdf has not been typed, and does not meet the requirements of any known type. 
	Warning: No statements found with predicate: <http://rdfs.org/ns/void#exampleResource>
		Please add one or more statement with predicate <http://rdfs.org/ns/void#exampleResource> and type A URI.
```

@ltatakis - any idea? Do we need to add those things to the form?

**Comment by ltatakis** [comment] 2017-05-20 11:04
Hi, @randykerber @stain  the dependency of the validator has been removed. Therefore, this shouldn't be an issue anymore.
The validator was removed as it was deprecated and not locatable in `http://repository.mygrid.org.uk/artifactory/ops` see #4 .

**Comment by ltatakis** [comment] 2017-05-20 11:05
Closing this issue. Please reopen if you are still having issues.

**Closed by ltatakis** 2017-05-20 11:05 UTC
